<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/ToiNoMori.Api/ToiNoMori.Api.csproj" />
    <ProjectReference Include="../ToiNoMori.Testing/ToiNoMori.Testing.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Compile Include="../ToiNoMori.Api.Tests/TestHeaderAuthenticationHandler.cs" Link="TestHeaderAuthenticationHandler.cs" />
  </ItemGroup>
</Project>
