<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <ProjectReference Include="../../src/ToiNoMori.Api/ToiNoMori.Api.csproj" />
    <ProjectReference Include="../ToiNoMori.Testing/ToiNoMori.Testing.csproj" />
  </ItemGroup>
</Project>
